import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    logo:{
        alignItems: 'center',
        width:"90%",
        height:"90%",
        alignContent:"center",
        alignSelf:"center"   
    },
    blue:{
        width:50,
        height:50,
        borderRadius:100,
        borderColor:"grey",
        borderWidth:1,left:"40%",
        marginTop:10
    },
    c:{
        width:80,
        height:80,
        left:-70,
    },
    set:{
        width:80,
        height:80,
        left:70,
    },
    meter:{
        width:270,
        height:270,
        borderWidth:3,
        borderColor:"#340C0C",
        backgroundColor:"#340C0C",
        borderRadius:200
    },
    meter3:{
        width:270,
        height:270,
        borderWidth:3,
        borderColor:"#D81B1B",
        backgroundColor:"#D81B1B",
        borderRadius:200
    },
    meter2:{
        width:230,
        height:230,
        alignItems:"center",
        alignSelf:"center",
        alignContent:"center",
        top:"7%",
        position:"absolute",
        borderWidth:3,
        borderColor:"#340C0C",
        backgroundColor:"#000000",
        borderRadius:210
    },
    mid:{
        width:80,
        height:80,
        left:0,
    },
    line:{
        borderColor:"#EE3936",
        color:'grey',
        backgroundColor:'grey',
        height:1,
        width:'90%',
        margin:'2%'
    },
    bulb:{
        width:"17%",
        height:"10%",
        borderRadius:100,
        borderColor:"grey",
        borderWidth:1,left:"-35%",
        top:"4%"
    },
    met:{
        width:"17%",
        height:"10%",
        borderRadius:100,
        borderColor:"grey",
        borderWidth:1,
        left:"-35%",
        top:"10%"
    },
    health:{
        width:"17%",
        height:"10%",
        borderRadius:100,
        borderColor:"grey",
        borderWidth:1,left:"35%",
        top:"-10%",
    },
    flash:{
        width:"17%",
        height:"10%",
        borderRadius:100,
        borderColor:"grey",
        borderWidth:1,
        left:"35%",
        top:"-16%"
    },
    body:{
        backgroundColor:'#000000',
        height:'100%',
        flex:1
    },
});

export default styles