import { StyleSheet } from "react-native";
import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';

const styles = StyleSheet.create({
    logo:{
        alignItems: 'center',
        width:"90%",
        height:"90%",
        paddingTop:20,
        alignContent:"center",
        alignSelf:"center",
    },
    boardview:{
        width:"-60%",
        height:"15%"
    },
    img:{  
        alignContent:"center",
        alignItems:"center"
    },
    img2:{
        alignContent:"center",
        alignItems:"center",
        width:"235%",//330,
        position:"absolute",
        top:"4.3%",//30,
        left:-65,
        height:610,//495,
        borderRadius:500
    },
    img3:{
        alignContent:"center",
        alignItems:"center",
        width:330,
        position:"absolute",
        top:36,
        left:-65,
        height:hp("20%"),
        borderWidth:3,
        borderColor:"#EE3936",
        borderRadius:500
    },
    body:{
        backgroundColor:'#000000',
        height:'100%',
        width:'100%'
    },
    btnComponent:{
        color:'#101010',  
    },
    button:{
        backgroundColor:'#000000',
        width:200,
    },
    buttonText:{
        textAlign:"center",
        fontFamily:"monster-semi",
        borderWidth:3,
        borderColor:"#EE3936",
        borderTopLeftRadius: 25,
        borderBottomRightRadius:25,
        marginBottom:"10%",
        color:'#EE3936',
        alignContent:"center",
        alignItems:"center",
        padding:10,
        paddingBottom:10,
        fontSize:20, 
    },
    button1:{
        backgroundColor:'#000000',
        width:200,
        left:'20%',
    },
    buttonText1:{
        textAlign:"center",
        borderWidth:3,
        borderColor:"#EE3936",
        borderBottomRightRadius: 25,
        fontFamily:"monster-semi",
        color:'#EE3936',
        alignContent:"center",
        alignItems:"center",
        paddingTop:10,
        paddingBottom:10,
        fontSize:20
    },
    button2:{
        backgroundColor:'#000000',
        width:wp("55%"),
        padding:'10%',
        alignContent:'center',
        alignSelf:"center",
    },
    buttonText2:{
        textAlign:"center",
        top:"10%",
        color:'#EE3936',
        fontFamily:"monster-semi",
        fontSize:30,
        width:335,
        height:hp("20%"),
        left:-100,
    },
    hover:{ 
        borderWidth:1,
        borderColor:"grey",
        backgroundColor:"#000000",
        borderRadius:100,
        position:"absolute",
        alignContent:"center",
        alignSelf:"center",
        width:80,
        top:100,
        height:40,
    },
    ad1:{
        borderWidth:1,
        borderColor:"grey",
        backgroundColor:"#000000",
        borderBottomRightRadius: 25,
        borderTopLeftRadius: 25,
        position:"absolute",
        alignContent:"center",
        alignSelf:"center",
        width:'180%',
        top:100,
        height:150,
        marginLeft:"8%"
    },
    rowstyles:{
        flexDirection:"row",
    },
    ad1img:{
        width:"53%",
        height:"60%",
        marginTop:"20%"
    },
    ad2:{
        borderWidth:1,
        borderColor:"grey",
        backgroundColor:"#000000",
        borderBottomRightRadius: 25,
        borderTopLeftRadius: 25,
        position:"absolute",
        alignContent:"center",
        alignSelf:"center",
        width:'180%',
        top:260,
        height:150,
        marginLeft:"5%"
    },
    ad2img:{
        width:"53%",
        height:"60%",
        marginTop:"20%"
    },
    ad3:{  
        borderWidth:1,
        borderColor:"grey",
        backgroundColor:"#000000",
        borderBottomRightRadius: 25,
        borderTopLeftRadius: 25,
        position:"absolute",
        alignContent:"center",
        alignSelf:"center",
        width:'180%',
        top:420,
        height:150,
        marginLeft:"5%"
    },
    ad3img:{
        width:"53%",
        height:"60%",
        marginTop:"20%"
    },
    circle:{
        borderWidth:3,
        borderColor:"#000000",
        backgroundColor:"#EE3936",
        borderRadius:100,
        position:"absolute",
        left:63,
        width:35,
        top:103,
        height:35, 
    },
    button3:{
        backgroundColor:'#000000',
        width:"63%",
        padding:'10%',
        alignContent:'center',
        alignSelf:"center",
    },
    buttonText3:{
        textAlign:"center",
        borderWidth:3,
        borderColor:"#EE3936",
        borderRadius:300,
        color:'#EE3936',
        alignContent:"center",
        alignItems:"center",
        width:"239%",
        height:610,
        left:-100,       
        fontSize:20
    },
    shadowProp: {
        shadowColor: '#171717',
        shadowOffset: {width: -2, height: 4},
        shadowOpacity: 0.2,
        shadowRadius: 3,
      },
    ad1text:{
        color:'#EE3936',
        fontFamily:'monster-semi',
        fontSize:13,
        top:"20%"
    },
    ad2text:{
        color:'#EE3936',
        fontFamily:'monster-semi',
        fontSize:13,
        marginTop:"20%",
        textAlign:"center",
        alignSelf:"center",
        marginLeft:"-5%",
    },
    ad3text:{
        color:'#EE3936',
        fontFamily:'monster-semi',
        fontSize:13,
        marginTop:"20%",
        textAlign:"center",
        alignSelf:"center",
        marginLeft:"-6%",
    },
    adtext1:{     
        borderWidth:3,
        borderColor:"#EE3936",
        borderRadius:300,
        color:'#EE3936',
        width:"90%",
        height:"100%",
        left:-100,
        fontSize:20
    },
    text1:{
        flexDirection:"row",
        paddingTop:30,
        paddingBottom:30,
        marginLeft:"-40%",
        alignContent:"space-between"
    },
});

export default styles